name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to report a bug! Please fill out the details below.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is.
      placeholder: When I do X, Y happens instead of Z.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Open Ziyada
        2. Go to the Search tab
        3. Type "..."
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Terminal output
      description: If applicable, paste screenshots or terminal output.
  - type: input
    id: os
    attributes:
      label: Windows version
      placeholder: "Windows 11 24H2"
    validations:
      required: true
  - type: input
    id: winget-version
    attributes:
      label: winget version
      description: "Run `winget --version` to find this."
      placeholder: "v1.12.460"
    validations:
      required: true
  - type: input
    id: ziyada-version
    attributes:
      label: Ziyada version
      placeholder: "v0.1.0"
    validations:
      required: true
  - type: input
    id: terminal
    attributes:
      label: Terminal application
      placeholder: "Windows Terminal, cmd, PowerShell, etc."
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Anything else that might be relevant.
