name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Thanks for suggesting a feature! Please describe what you'd like to see.
  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What problem does this solve? Is this related to a frustration?
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe how you'd like this to work.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you've considered?
  - type: dropdown
    id: area
    attributes:
      label: Area of the application
      options:
        - Search & Install
        - Installed Packages
        - Upgrades
        - Sources
        - Export/Import
        - UI/Theme
        - Performance
        - Configuration
        - Other
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Mockups, screenshots, or any other context.
